

USE DATABASE ATTENDANCE_DB;
CREATE SCHEMA IF NOT EXISTS ATTENDANCE_DB.DATA_MART;
USE SCHEMA DATA_MART;

-- Creating Dimension Student,course,date and  attedance  as facts


CREATE OR REPLACE TABLE DIM_STUDENT (
    STUDENT_KEY NUMBER AUTOINCREMENT,
    STUDENT_ID NUMBER,
    STUDENT_NAME VARCHAR,
    GENDER VARCHAR,
    DOB DATE,
    EMAIL_ADDRESS VARCHAR,
    PHONE_NUMBER VARCHAR,
    COURSE_ID NUMBER,
    DEPARTMENT VARCHAR,
    SEMESTER VARCHAR,
    ADMISSION_DATE DATE,
    CITY VARCHAR,
    STATE VARCHAR,
    STATUS VARCHAR,
    CREATED_DATE TIMESTAMP_NTZ,
    UPDATED_DATE TIMESTAMP_NTZ,
    CONSTRAINT PK_DIM_STUDENT PRIMARY KEY (STUDENT_KEY)
);


CREATE OR REPLACE TABLE DIM_COURSE (
    COURSE_KEY NUMBER AUTOINCREMENT,
    COURSE_ID NUMBER,
    COURSE_NAME VARCHAR,
    DEPARTMENT VARCHAR,
    COURSE_CATEGORY VARCHAR,
    INSTRUCTOR_NAME VARCHAR,
    CREDITS NUMBER,
    COURSE_DURATION VARCHAR,
    START_DATE DATE,
    END_DATE DATE,
    BATCH NUMBER,
    ACAD_YEAR VARCHAR,
    STATUS VARCHAR,
    CREATION_DATE TIMESTAMP_NTZ,
    CONSTRAINT PK_DIM_COURSE PRIMARY KEY (COURSE_KEY)
);



CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY NUMBER,
    FULL_DATE DATE,
    DAY NUMBER,
    DAY_NAME VARCHAR,
    MONTH NUMBER,
    MONTH_NAME VARCHAR,
    QUARTER NUMBER,
    YEAR NUMBER,
    YEAR_MONTH VARCHAR,
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);

-- FACT: ATTENDANCE

CREATE OR REPLACE TABLE ATTENDANCE (
    ATTENDANCE_KEY NUMBER AUTOINCREMENT,
    ATTENDANCE_ID NUMBER,
    STUDENT_KEY NUMBER,
    COURSE_KEY NUMBER,
    DATE_KEY NUMBER,
    ATTENDANCE_STATUS VARCHAR,
    CHECK_IN_TIME TIMESTAMP_NTZ,
    CHECK_OUT_TIME TIMESTAMP_NTZ,
    ATTENDANCE_PERCENTAGE NUMBER(5,2),
    RECORDED_BY VARCHAR,
    CREATED_TIMESTAMP TIMESTAMP_NTZ,
    CONSTRAINT PK_ATTENDANCE PRIMARY KEY (ATTENDANCE_KEY)
);

-- ERROR LOG

CREATE OR REPLACE TABLE ETL_ERROR_LOG (
    ERROR_ID NUMBER AUTOINCREMENT,
    ERROR_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROCESS_NAME VARCHAR,
    ATTENDANCE_ID NUMBER,
    STUDENT_ID NUMBER,
    COURSE_ID NUMBER,
    ATTENDANCE_DATE DATE,
    ERROR_TYPE VARCHAR,
    ERROR_MESSAGE VARCHAR
);

-- LOAD STUDENT DIMENSION

INSERT INTO DIM_STUDENT (
    STUDENT_ID, STUDENT_NAME, GENDER, DOB, EMAIL_ADDRESS,
    PHONE_NUMBER, COURSE_ID, DEPARTMENT, SEMESTER, ADMISSION_DATE,
    CITY, STATE, STATUS, CREATED_DATE, UPDATED_DATE
)
SELECT DISTINCT
    STUDENT_ID, STUDENT_NAME, GENDER, DOB, EMAIL, PHONE_NO,
    COURSE_ID, DEPARTMENT, SEMESTER, ADMISSION_DATE, CITY,
    STUDENT_STATE, STUDENT_STATUS,
    CREATION_DATE::TIMESTAMP_NTZ,
    UPDATE_DATE::TIMESTAMP_NTZ
FROM ATTENDANCE_DB.STAGING.STG_STUDENT;

-- LOAD COURSE DIMENSION

INSERT INTO DIM_COURSE (
    COURSE_ID, COURSE_NAME, DEPARTMENT, COURSE_CATEGORY,
    INSTRUCTOR_NAME, CREDITS, COURSE_DURATION, START_DATE,
    END_DATE, BATCH, ACAD_YEAR, STATUS, CREATION_DATE
)
SELECT
    COURSE_ID, COURSE_NAME, DEPARTMENT, COURSE_CATEGORY,
    INSTRUCTOR_NAME, CREDITS, COURSE_DURATION, START_DATE,
    END_DATE, BATCH, ACAD_YEAR, STATUS, CURRENT_TIMESTAMP()
FROM ATTENDANCE_DB.STAGING.STG_COURSE;

-- LOAD DATE DIMENSION

INSERT INTO DIM_DATE (
    DATE_KEY, FULL_DATE, DAY, DAY_NAME, MONTH, MONTH_NAME,
    QUARTER, YEAR, YEAR_MONTH
)
SELECT
    TO_NUMBER(TO_CHAR(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE), 'YYYYMMDD')),
    DATEADD(DAY, SEQ4(), '2026-07-27'::DATE),
    DAY(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE)),
    DAYNAME(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE)),
    MONTH(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE)),
    MONTHNAME(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE)),
    QUARTER(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE)),
    YEAR(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE)),
    TO_CHAR(DATEADD(DAY, SEQ4(), '2026-07-27'::DATE), 'YYYY-MM')
FROM TABLE(GENERATOR(ROWCOUNT => 128));

-- Initial fact load

INSERT INTO ATTENDANCE (
    ATTENDANCE_ID, STUDENT_KEY, COURSE_KEY, DATE_KEY,
    ATTENDANCE_STATUS, CHECK_IN_TIME, CHECK_OUT_TIME,
    ATTENDANCE_PERCENTAGE, RECORDED_BY, CREATED_TIMESTAMP
)
SELECT
    A.ATTENDANCE_ID, S.STUDENT_KEY, C.COURSE_KEY, D.DATE_KEY,
    A.ATTENDANCE_STATUS, A.CHECK_IN_TIME, A.CHECK_OUT_TIME,
    A.ATTENDANCE_PERCENTAGE, A.RECORDED_BY, A.CREATED_TIMESTAMP
FROM ATTENDANCE_DB.STAGING.STG_ATTENDANCE A
JOIN DIM_STUDENT S ON A.STUDENT_ID = S.STUDENT_ID
JOIN DIM_COURSE C ON A.COURSE_ID = C.COURSE_ID
JOIN DIM_DATE D ON A.ATTENDANCE_DATE = D.FULL_DATE;

-- Delta stream

CREATE OR REPLACE STREAM ATTENDANCE_DB.STAGING.STG_ATTENDANCE_STREAM
ON TABLE ATTENDANCE_DB.STAGING.STG_ATTENDANCE;

-- Validating procedure

CREATE OR REPLACE PROCEDURE ATTENDANCE_DB.DATA_MART.LOAD_ATTENDANCE_FACT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN

    CREATE OR REPLACE TEMPORARY TABLE TMP_ATTENDANCE AS
    SELECT *
    FROM ATTENDANCE_DB.STAGING.STG_ATTENDANCE_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO ATTENDANCE_DB.DATA_MART.ETL_ERROR_LOG (
        PROCESS_NAME, ATTENDANCE_ID, STUDENT_ID, COURSE_ID,
        ATTENDANCE_DATE, ERROR_TYPE, ERROR_MESSAGE
    )
    SELECT
        'LOAD_ATTENDANCE_FACT',
        A.ATTENDANCE_ID,
        A.STUDENT_ID,
        A.COURSE_ID,
        A.ATTENDANCE_DATE,
        CASE
            WHEN S.STUDENT_KEY IS NULL THEN 'INVALID_STUDENT'
            WHEN C.COURSE_KEY IS NULL THEN 'INVALID_COURSE'
            WHEN D.DATE_KEY IS NULL THEN 'INVALID_DATE'
        END,
        CASE
            WHEN S.STUDENT_KEY IS NULL
                THEN 'Student ID does not exist in DIM_STUDENT'
            WHEN C.COURSE_KEY IS NULL
                THEN 'Course ID does not exist in DIM_COURSE'
            WHEN D.DATE_KEY IS NULL
                THEN 'Attendance date does not exist in DIM_DATE'
        END
    FROM TMP_ATTENDANCE A
    LEFT JOIN DIM_STUDENT S ON A.STUDENT_ID = S.STUDENT_ID
    LEFT JOIN DIM_COURSE C ON A.COURSE_ID = C.COURSE_ID
    LEFT JOIN DIM_DATE D ON A.ATTENDANCE_DATE = D.FULL_DATE
    WHERE S.STUDENT_KEY IS NULL
       OR C.COURSE_KEY IS NULL
       OR D.DATE_KEY IS NULL;

    MERGE INTO ATTENDANCE T
    USING (
        SELECT
            A.ATTENDANCE_ID,
            S.STUDENT_KEY,
            C.COURSE_KEY,
            D.DATE_KEY,
            A.ATTENDANCE_STATUS,
            A.CHECK_IN_TIME,
            A.CHECK_OUT_TIME,
            A.ATTENDANCE_PERCENTAGE,
            A.RECORDED_BY,
            A.CREATED_TIMESTAMP
        FROM TMP_ATTENDANCE A
        JOIN DIM_STUDENT S ON A.STUDENT_ID = S.STUDENT_ID
        JOIN DIM_COURSE C ON A.COURSE_ID = C.COURSE_ID
        JOIN DIM_DATE D ON A.ATTENDANCE_DATE = D.FULL_DATE
    ) SRC
    ON T.ATTENDANCE_ID = SRC.ATTENDANCE_ID

    WHEN NOT MATCHED THEN
        INSERT (
            ATTENDANCE_ID, STUDENT_KEY, COURSE_KEY, DATE_KEY,
            ATTENDANCE_STATUS, CHECK_IN_TIME, CHECK_OUT_TIME,
            ATTENDANCE_PERCENTAGE, RECORDED_BY, CREATED_TIMESTAMP
        )
        VALUES (
            SRC.ATTENDANCE_ID, SRC.STUDENT_KEY, SRC.COURSE_KEY,
            SRC.DATE_KEY, SRC.ATTENDANCE_STATUS, SRC.CHECK_IN_TIME,
            SRC.CHECK_OUT_TIME, SRC.ATTENDANCE_PERCENTAGE,
            SRC.RECORDED_BY, SRC.CREATED_TIMESTAMP
        );

    RETURN 'Attendance load and validation completed';

END;
$$;

-- Auto incremental load 

CREATE OR REPLACE TASK ATTENDANCE_DB.DATA_MART.LOAD_ATTENDANCE_TASK
    WAREHOUSE = ATTENDANCE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'ATTENDANCE_DB.STAGING.STG_ATTENDANCE_STREAM'
    )
AS
    CALL ATTENDANCE_DB.DATA_MART.LOAD_ATTENDANCE_FACT();

ALTER TASK ATTENDANCE_DB.DATA_MART.LOAD_ATTENDANCE_TASK RESUME;

-- VALIDATION

SELECT
    (SELECT COUNT(*) FROM ATTENDANCE_DB.STAGING.STG_STUDENT) AS STG_STUDENTS,
    (SELECT COUNT(*) FROM DIM_STUDENT) AS DIM_STUDENTS,
    (SELECT COUNT(*) FROM ATTENDANCE_DB.STAGING.STG_COURSE) AS STG_COURSES,
    (SELECT COUNT(*) FROM DIM_COURSE) AS DIM_COURSES,
    (SELECT COUNT(*) FROM ATTENDANCE_DB.STAGING.STG_ATTENDANCE) AS STG_ATTENDANCE,
    (SELECT COUNT(*) FROM ATTENDANCE) AS FACT_ATTENDANCE;

SELECT ATTENDANCE_ID, COUNT(*) AS DUPLICATE_COUNT
FROM ATTENDANCE
GROUP BY ATTENDANCE_ID
HAVING COUNT(*) > 1
ORDER BY DUPLICATE_COUNT DESC;

SELECT COUNT(*) AS INVALID_STUDENTS
FROM ATTENDANCE
WHERE STUDENT_KEY IS NULL;

SELECT COUNT(*) AS INVALID_COURSES
FROM ATTENDANCE
WHERE COURSE_KEY IS NULL;

SELECT COUNT(*) AS INVALID_DATES
FROM ATTENDANCE
WHERE DATE_KEY IS NULL;

SELECT *
FROM ETL_ERROR_LOG
ORDER BY ERROR_ID;
