-- STUDENT ATTENDANCE ANALYTICS PLATFORM
-- SNOWFLAKE PLATFORM SETUP & DATA INGESTION
-- GitHub-safe version: no Azure SAS tokens, passwords, or secrets.

CREATE WAREHOUSE IF NOT EXISTS ATTENDANCE_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE ATTENDANCE_WH;

CREATE DATABASE IF NOT EXISTS ATTENDANCE_DB;
CREATE SCHEMA IF NOT EXISTS ATTENDANCE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS ATTENDANCE_DB.DATA_MART;

USE DATABASE ATTENDANCE_DB;
USE SCHEMA STAGING;

-- STAGING TABLES

CREATE OR REPLACE TABLE STG_COURSE (
    COURSE_ID NUMBER,
    COURSE_NAME VARCHAR,
    DEPARTMENT VARCHAR,
    COURSE_CATEGORY VARCHAR,
    INSTRUCTOR_NAME VARCHAR,
    CREDITS NUMBER,
    COURSE_DURATION VARCHAR,
    START_DATE DATE,
    END_DATE DATE,
    BATCH NUMBER,
    ACAD_YEAR VARCHAR,
    STATUS VARCHAR,
    CREATION_DATE TIMESTAMP
);

CREATE OR REPLACE TABLE STG_STUDENT (
    STUDENT_ID NUMBER,
    STUDENT_NAME VARCHAR,
    GENDER VARCHAR,
    DOB DATE,
    EMAIL VARCHAR,
    PHONE_NO VARCHAR,
    COURSE_ID NUMBER,
    DEPARTMENT VARCHAR,
    SEMESTER NUMBER,
    ADMISSION_DATE DATE,
    CITY VARCHAR,
    STUDENT_STATE VARCHAR,
    STUDENT_STATUS VARCHAR,
    CREATION_DATE TIMESTAMP_TZ,
    UPDATE_DATE TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE STG_ATTENDANCE (
    ATTENDANCE_ID NUMBER,
    STUDENT_ID NUMBER,
    COURSE_ID NUMBER,
    ATTENDANCE_DATE DATE,
    CHECK_IN_TIME TIMESTAMP,
    CHECK_OUT_TIME TIMESTAMP,
    ATTENDANCE_STATUS VARCHAR,
    ATTENDANCE_PERCENTAGE NUMBER(5,2),
    RECORDED_BY VARCHAR,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- CSV FILE FORMAT

CREATE OR REPLACE FILE FORMAT ATTENDANCE_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

-- AZURE STORAGE INTEGRATION
-- Configure these values for your own Azure environment.
-- Never commit real tenant secrets, SAS tokens, connection strings,
-- or account keys to GitHub.

-- CREATE OR REPLACE STORAGE INTEGRATION AZURE_ATTENDANCE_INTEGRATION
--     TYPE = EXTERNAL_STAGE
--     STORAGE_PROVIDER = AZURE
--     ENABLED = TRUE
--     AZURE_TENANT_ID = '<YOUR_AZURE_TENANT_ID>'
--     STORAGE_ALLOWED_LOCATIONS = (
--         'azure://<STORAGE_ACCOUNT>.blob.core.windows.net/<CONTAINER>/'
--     );

-- AZURE STAGES
-- Example configuration using the storage integration:

-- CREATE OR REPLACE STAGE AZURE_STUDENT_STAGE
--     URL = 'azure://<STORAGE_ACCOUNT>.blob.core.windows.net/<CONTAINER>/'
--     STORAGE_INTEGRATION = AZURE_ATTENDANCE_INTEGRATION
--     FILE_FORMAT = ATTENDANCE_CSV_FORMAT;

-- CREATE OR REPLACE STAGE AZURE_COURSE_STAGE
--     URL = 'azure://<STORAGE_ACCOUNT>.blob.core.windows.net/<CONTAINER>/'
--     STORAGE_INTEGRATION = AZURE_ATTENDANCE_INTEGRATION
--     FILE_FORMAT = ATTENDANCE_CSV_FORMAT;

-- CREATE OR REPLACE STAGE AZURE_ATTENDANCE_STAGE
--     URL = 'azure://<STORAGE_ACCOUNT>.blob.core.windows.net/<CONTAINER>/'
--     STORAGE_INTEGRATION = AZURE_ATTENDANCE_INTEGRATION
--     FILE_FORMAT = ATTENDANCE_CSV_FORMAT;

-- BATCH LOAD EXAMPLE

-- COPY INTO STG_COURSE
-- FROM @AZURE_COURSE_STAGE
-- PATTERN = '.*Course\.csv'
-- ON_ERROR = 'CONTINUE';

-- SNOWPIPE AUTO-INGEST
-- Azure notification integrations require environment-specific
-- queue URLs and tenant configuration.

-- CREATE OR REPLACE NOTIFICATION INTEGRATION AZURE_STUDENT_NOTIFICATION
--     TYPE = QUEUE
--     NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
--     AZURE_STORAGE_QUEUE_PRIMARY_URI =
--         'https://<STORAGE_ACCOUNT>.queue.core.windows.net/<STUDENT_QUEUE>'
--     AZURE_TENANT_ID = '<YOUR_AZURE_TENANT_ID>'
--     ENABLED = TRUE;

-- CREATE OR REPLACE PIPE STUDENT_PIPE
--     AUTO_INGEST = TRUE
--     INTEGRATION = 'AZURE_STUDENT_NOTIFICATION'
-- AS
--     COPY INTO STG_STUDENT
--     FROM @AZURE_STUDENT_STAGE
--     PATTERN = '.*Student.*[.]csv'
--     ON_ERROR = 'CONTINUE';

-- CREATE OR REPLACE NOTIFICATION INTEGRATION AZURE_ATTENDANCE_NOTIFICATION
--     TYPE = QUEUE
--     NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
--     AZURE_STORAGE_QUEUE_PRIMARY_URI =
--         'https://<STORAGE_ACCOUNT>.queue.core.windows.net/<ATTENDANCE_QUEUE>'
--     AZURE_TENANT_ID = '<YOUR_AZURE_TENANT_ID>'
--     ENABLED = TRUE;

-- CREATE OR REPLACE PIPE ATTENDANCE_PIPE
--     AUTO_INGEST = TRUE
--     INTEGRATION = 'AZURE_ATTENDANCE_NOTIFICATION'
-- AS
--     COPY INTO STG_ATTENDANCE
--     FROM @AZURE_ATTENDANCE_STAGE
--     PATTERN = '.*Attendance.*[.]csv'
--     ON_ERROR = 'CONTINUE';

-- MONITORING

SELECT COUNT(*) AS STG_STUDENT_COUNT FROM STG_STUDENT;
SELECT COUNT(*) AS STG_COURSE_COUNT FROM STG_COURSE;
SELECT COUNT(*) AS STG_ATTENDANCE_COUNT FROM STG_ATTENDANCE;
